name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: "user-game-bejs"
      HEROKU_EMAIL: ${{secrets.HEROKU_EMAIL}}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SOME_API_KEY: "123456abcdef"
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_PROD_DB_USERNAME: ${{secrets.DB_USERNAME}}
          envkey_PROD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          envkey_PROD_DB_NAME: ${{secrets.DB_NAME}}
          envkey_PROD_DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
          envkey_PROD_DB_PORT: ${{secrets.DB_PORT}}
          envkey_PROD_DB_DIALECT: ${{secrets.DB_DIALECT}}
          envkey_HEROKU_API_KEY: echo $HEROKU_API_KEY
          envkey_HEROKU_APP_NAME: echo $HEROKU_APP_NAME
          envkey_HEROKU_EMAIL: echo $HEROKU_EMAIL
      - name: Install dependencies
        run: npm install
      - name: Show .env file
        run: cat .env
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      - name: Migrate DB
        run: npx sequelize db:migrate --env production
      - name: Seeding DB
        run: npx sequelize db:seed:all --env production
      # - name: Test
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env: 
      ENV_VARIABLE: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "user-game-bejs"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
