name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      DB_USERNAME: "pfzqxocydqvswt"
      DB_PASSWORD: "13db1dc4371c19e7c780bec629b40da515c49865049e82f5055e01e470505946"
      DB_NAME: "d3juovg27i85ot"
      DB_HOSTNAME: "ec2-52-4-104-184.compute-1.amazonaws.com"
      DB_PORT: 5432
      DB_DIALECT: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Make envfile
        run: |
          touch ../../.env 
          echo "PROD_DB_USERNAME=${DB_USERNAME}" >> ../../.env 
          echo "PROD_DB_PASSWORD=${DB_PASSWORD}" >> ../../.env
          echo "PROD_DB_NAME=${DB_NAME}" >> ../../.env
          echo "PROD_DB_HOSTNAME=${DB_HOSTNAME}" >> ../../.env
          echo "PROD_DB_PORT=${DB_PORT}" >> ../../.env
          echo "PROD_DB_DIALECT=${DB_DIALECT}" >> ../../.env
      - name: Show .env file
        run: cat ../../.env
      - name: Install dependencies
        run: npm install
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      - name: Migrate DB
        run: npx sequelize db:migrate --env production
      - name: Seeding DB
        run: npx sequelize db:seed:all --env production
      # - name: Test
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env: 
      ENV_VARIABLE: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "user-game-bejs"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
