name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Install dependencies
        run: npm install
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      # - name: Migrate DB
      #  run: npx sequelize db:migrate --env production
      # - name: Test
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: HEROKU_API_KEY
          heroku_app_name: "user-game-bejs"
          heroku_email: "fauzanjr1@gmail.com"