name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      environment: PROD
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
      - name: See secrets
        run: |
          echo ${{ env.DB_USERNAME }}
          echo ${{secrets.HEROKU_API_KEY}}
      - name: Add .env file
        run: |
          touch .env
          echo PROD_DB_USERNAME=${{env.DB_USERNAME}} >> .env
          echo PROD_DB_PASSWORD=${{env.DB_PASSWORD}} >> .env
          echo PROD_DB_NAME=${{env.DB_NAME}} >> .env
          echo PROD_DB_HOSTNAME=${{env.DB_HOSTNAME}} >> .env
          echo PROD_DB_PORT=${{env.DB_PORT}} >> .env
          echo PROD_DB_DIALECT=${{env.DB_DIALECT}} >> .env
          cat .env
      - name: Install sequlize-cli
        run: npm install sequelize-cli
      - name: Migrate DB
        run: npx sequelize db:migrate --env production
      - name: Seeding DB
        run: npx sequelize db:seed:all --env production
      # - name: Test
      #   run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env: 
      ENV_VARIABLE: PROD
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "user-game-bejs"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
